import { SearchItem } from './types';

export const STATIC_PAGES: SearchItem[] = [
  {
    id: 'page-home',
    type: 'page',
    title: 'Home',
    description: 'Sync Apple Health to a backend you run yourself — open source, Apache-2.0',
    href: '/',
    icon: 'Home',
  },
  {
    id: 'page-app',
    type: 'page',
    title: 'App',
    description: 'The open-source iOS app that syncs Apple Health to your own server',
    href: '/app',
    icon: 'Smartphone',
  },
  {
    id: 'page-sync',
    type: 'page',
    title: 'Self-Hosted Server',
    description: 'The open-source reference backend: Postgres, TimescaleDB, Grafana and a web viewer via Docker Compose',
    href: '/sync',
    icon: 'Server',
  },
  {
    id: 'page-consulting',
    type: 'page',
    title: 'Consulting',
    description: 'Help setting up, self-hosting, and building with PulsHealth — from the person who wrote it',
    href: '/consulting',
    icon: 'Users',
  },
  {
    id: 'page-support',
    type: 'page',
    title: 'Support',
    description: 'Documentation, issue tracker, and how to get help',
    href: '/support',
    icon: 'HelpCircle',
  },
  {
    id: 'page-about',
    type: 'page',
    title: 'About',
    description: 'Learn about PulsHealth and our mission',
    href: '/about',
    icon: 'Info',
  },
  {
    id: 'page-knowledge-base',
    type: 'page',
    title: 'Knowledge Base',
    description: 'Explore Apple HealthKit data types and documentation',
    href: '/knowledge-base',
    icon: 'BookOpen',
  },
  {
    id: 'page-knowledge-base-explore',
    type: 'page',
    title: 'Explore Health Data Types',
    description: 'Browse and search all HealthKit data types',
    href: '/knowledge-base/explore',
    icon: 'Search',
  },
  {
    id: 'page-blog',
    type: 'page',
    title: 'Blog',
    description: 'Articles and insights about health data and technology',
    href: '/blog',
    icon: 'Newspaper',
  },
  {
    id: 'page-privacy',
    type: 'page',
    title: 'Privacy Policy',
    description: 'Where your health data goes, and where it does not',
    href: '/privacy',
    icon: 'Shield',
  },
  {
    id: 'page-terms',
    type: 'page',
    title: 'Terms of Service',
    description: 'Terms and conditions for using PulsHealth',
    href: '/terms',
    icon: 'FileText',
  },
];
