import { SearchItem } from './types';

export const STATIC_PAGES: SearchItem[] = [
  {
    id: 'page-home',
    type: 'page',
    title: 'Home',
    description: 'The free iPhone app to explore, export and sync Apple Health to a database, hosted for you or self-hosted, and connect any AI agent over MCP. Open source, Apache-2.0',
    href: '/',
    icon: 'Home',
  },
  {
    id: 'page-sync',
    type: 'page',
    title: 'Self-hosting',
    description: 'Run the open-source PulsHealth database yourself: PostgreSQL with TimescaleDB, Grafana, a web viewer, an API and an MCP server via Docker Compose',
    href: '/server',
    icon: 'Database',
  },
  {
    id: 'page-consulting',
    type: 'page',
    title: 'Consulting',
    description: 'Help with health data and AI: pipelines, models and evaluation',
    href: '/consulting',
    icon: 'Users',
  },
  {
    id: 'page-support',
    type: 'page',
    title: 'Support',
    description: 'Documentation, issue tracker, and how to get help',
    href: '/support',
    icon: 'HelpCircle',
  },
  {
    id: 'page-about',
    type: 'page',
    title: 'About',
    description: 'Why PulsHealth exists, who makes it, and how it compares with other Apple Health exporters',
    href: '/about',
    icon: 'Info',
  },
  {
    id: 'page-knowledge-base',
    type: 'page',
    title: 'Knowledge Base',
    description: 'Explore Apple HealthKit data types and documentation',
    href: '/knowledge-base',
    icon: 'BookOpen',
  },
  {
    id: 'page-knowledge-base-explore',
    type: 'page',
    title: 'Explore Health Data Types',
    description: 'Browse and search all HealthKit data types',
    href: '/knowledge-base/explore',
    icon: 'Search',
  },
  {
    id: 'page-docs',
    type: 'page',
    title: 'Documentation',
    description: 'The sync protocol spec, self-hosting, AI assistants, bulk export and the database guide',
    href: '/docs',
    icon: 'BookOpen',
  },
  {
    id: 'page-blog',
    type: 'page',
    title: 'Blog',
    description: 'Articles and insights about health data and technology',
    href: '/blog',
    icon: 'Newspaper',
  },
  {
    id: 'page-privacy',
    type: 'page',
    title: 'Privacy Policy',
    description: 'Where your health data goes, and where it does not',
    href: '/privacy',
    icon: 'Shield',
  },
];
